version: 0.2

env:
  variables:
    DOTNET_ROOT: /root/.dotnet
  secrets-manager:
    LOCAL_SECRET_VAR: 'TestKey:Test'
phases:
  install:
    runtime-versions:
      dotnet: 3.1
      python: 3.8
    commands:
      - echo $LOCAL_SECRET_VAR
      - export APPLE=$LOCAL_SECRET_VAR
      - ls
      - envsubst < appsettings.dev.json > new.json
      - cat new.json
      - ( echo "cat <<EOF" ; cat appsettings.dev.json; echo EOF ) | sh
      - cat appsettings.dev.json
  build:
    commands:
      - echo Build started on `date`
