version: 0.2


env:
   variables:
     DOTNET_ROOT: /root/.dotnet
phases:
  install:
    runtime-versions:
      dotnet: 3.1
      nodejs: 10
      python: 3.8
  build:
    commands:
      - echo Build started on `date`
      - npm install -g cdk@1.89.0
      - cd $CODEBUILD_SRC_DIR/$APP_PROJECT_ROOT
      - python -m pip install -r requirements.txt
      - python app.py
    